alphabet = 'abcdefghijklmnopqrstuvwxyz'
print(alphabet[0:2])
print(alphabet[7:9])
print(alphabet[21:])
print(alphabet[19:])
print(alphabet[:3])
print(alphabet[:6])
print(alphabet[:])
print(alphabet[-3:])
print(alphabet[0:25:2])
print(alphabet[::2])
print(alphabet[1::2])
print(alphabet[::-1])
print(alphabet[4::-1])
print(alphabet[1:10:-1])
print(alphabet[10:1:-1])
print(alphabet[::-2])
print(alphabet.find('e'))
position = alphabet.find('e')
print(position)
print(alphabet[position:])
print(alphabet[alphabet.find('e'):])
print(alphabet.find('hello'))
print(alphabet.find('K'))
print(alphabet.find('k'))
